<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Dhruv Balwada · Columbia Climate School · Fall 2026">
  <title>Introduction to Climate Modeling – From a bucket to a planet</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="comments.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">From a bucket to a planet</h1>
  <p class="subtitle">Week 2</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dhruv Balwada · Columbia Climate School · Fall 2026
</div>
</div>
</div>

</section>
<section id="last-week-this-week" class="slide level2">
<h2>Last week, this week</h2>
<ul>
<li><strong>Last week:</strong> hub + GitHub, a Python warm-up, the climate of NYC — one thermometer, ERA5, eight CMIP6 models</li>
<li><strong>Today:</strong>
<ol type="1">
<li><strong>Lab 0d</strong> — a bucket: budgets, equilibrium, stepping forward in time</li>
<li><strong>What is uncertainty?</strong> — three reasons a forecast can be wrong</li>
<li><strong>The Earth <em>is</em> a bucket</strong> — the first climate calculation</li>
<li>If we get there: <strong>why is the surface warmer than the planet?</strong></li>
</ol></li>
</ul>
<aside class="notes">
<p>Hands: who has a working hub login? Who managed to push to GitHub? Then the GitHub slide — don’t debug on the projector; TAs circulate during the lab.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="github-a-simpler-way-to-log-in" class="slide level2 smaller">
<h2>GitHub: a simpler way to log in</h2>
<p>Last week <code>gh-scoped-creds</code> tripped many of you (the “select repositories” step, and the 8-hour expiry). New one-time setup — a <strong>personal access token</strong>:</p>
<ol type="1">
<li><p>On GitHub: profile photo → <strong>Settings → Developer settings → Personal access tokens → Tokens (classic) → Generate new token (classic)</strong>. Tick <code>repo</code>, expiry <strong>Dec 31, 2026</strong>, copy the token.</p></li>
<li><p>In a hub terminal:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a aria-label="1"></a><span class="fu">git</span> config <span class="at">--global</span> <span class="at">--unset-all</span> credential.helper</span>
<span id="cb1-2"><a aria-label="2"></a><span class="fu">git</span> config <span class="at">--global</span> credential.helper store</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div></li>
<li><p>Next <code>git push</code>: username = your GitHub username, password = <strong>paste the token</strong> (nothing appears as you paste). It is saved; you won’t be asked again.</p></li>
</ol>
<p>Full instructions + common errors: <strong><a href="https://dhruvbalwada.github.io/intro-climate-modeling-fall2026/labs/github_setup.html">GitHub on the LEAP hub</a></strong></p>
<aside class="notes">
<p>The page also keeps gh-scoped-creds as an alternative, with the missing step spelled out (adding the repo to the app’s list at github.com/settings/installations). Repo link on Courseworks remains the submission.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section>
<section id="lab-0d-modeling-using-budgets" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>Lab 0d · Modeling using budgets</h1>

</section>
<section id="the-plan" class="slide level2 smaller">
<h2>The plan</h2>
<ol type="1">
<li><strong>A budget:</strong> <span class="math inline">\(A\,\dfrac{dh}{dt} = F - Q_\mathrm{out}\)</span></li>
<li><strong>Two drain laws from two dominant balances:</strong> Torricelli <span class="math inline">\(Q \propto \sqrt{h}\)</span> · Poiseuille <span class="math inline">\(Q \propto h\)</span> — we adopt the linear one, <span class="math inline">\(Q = kh\)</span></li>
<li><strong>Equilibrium:</strong> <span class="math inline">\(h^* = F/k\)</span> — the level the bucket <em>wants</em></li>
<li><strong>Stepping in time:</strong> Euler, <span class="math inline">\(h_{n+1} = h_n + \Delta t\,(F - k h_n)/A\)</span></li>
<li><strong>Play:</strong> vary <span class="math inline">\(h_0\)</span>, <span class="math inline">\(k\)</span>, <span class="math inline">\(F\)</span> — keep the plots, they come back in ten minutes</li>
</ol>
<aside class="notes">
<p>The notebook drives; the board carries the derivations (they are written out in Lab 0d for reading later). Step 5 is what the uncertainty slides point back at.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- TOPIC BLOCK: what is uncertainty — three reasons + how they trade off with time.
     Written for week 1 (2026-09-10), not reached; now played in week 2 right after Lab 0d. -->
</section></section>
<section>
<section id="what-is-uncertainty" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>3 · What is uncertainty?</h1>

</section>
<section id="three-reasons-a-forecast-model-can-be-wrong" class="slide level2 smaller">
<h2>Three reasons a forecast model can be wrong</h2>
<blockquote>
<p>“It’s tough to make predictions, especially about the future.”</p>
</blockquote>
<p>You just generated all three in the bucket:</p>
<ul>
<li><strong>Initial-condition uncertainty</strong> — you varied <span class="math inline">\(h_0\)</span>: matters early, forgotten later <em>(Earth: today’s exact weather)</em></li>
<li><strong>Model uncertainty</strong> — you varied <span class="math inline">\(k\)</span>: parameters (and structure) <em>(Earth: we don’t know exact laws or our models can’t be exactly solved)</em></li>
<li><strong>Scenario uncertainty</strong> — you varied <span class="math inline">\(F\)</span>: the pourer decides, not physics <em>(Earth: emissions)</em></li>
</ul>
<p>Different ones dominate at different horizons.</p>
<aside class="notes">
<p>Every bullet points at something they DID today. Worth saying aloud: by 2100 the biggest uncertainty is the scenario — the largest unknown is a choice.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="how-the-three-trade-off-with-time" class="slide level2 smaller">
<h2>How the three trade off with time</h2>
<div class="columns">
<div class="column" style="width:50%;">
<img data-src="images/ipcc_ar6_faq4_1_temp.png" class="quarto-figure quarto-figure-center" height="320">
<div style="font-size:0.8em; line-height:1.2;">
Individual model runs under a low and a high scenario. For the next ~20 years the wiggles — <b>internal variability</b> — swamp the difference between scenarios.
</div>
</div><div class="column" style="width:50%;">
<img data-src="images/hawkins_fracvar_global_T.png" class="quarto-figure quarto-figure-center" height="320">
<div style="font-size:0.8em; line-height:1.2;">
Share of the uncertainty in <b>global, annual-mean, 10-year-averaged</b> temperature: <span style="color:#f28c00"><b>internal variability</b></span> dominates early, <span style="color:#1f1fff"><b>model uncertainty</b></span> mid-century, <span style="color:#0a7a0a"><b>scenario</b></span> by 2100. <em>That smoothing is why orange fades so fast — ask about one summer in one city and it stays orange much longer.</em>
</div>
</div></div>
<div style="font-size:0.35em; color:#888;">
Left: IPCC AR6 WG1 FAQ 4.1 (2021). Right: Hawkins &amp; Sutton (2009), updated for CMIP5 by E. Hawkins, Climate Lab Book, CC BY-SA 4.0.
</div>
<aside class="notes">
<p>Map the bucket onto the colours: varying h0 = orange, varying k = blue, varying F = green. Left panel is the intuition (you cannot tell the scenarios apart before ~2040); right panel is the bookkeeping. Closing line: by 2100 the biggest uncertainty is the scenario — the largest unknown is a choice.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- TOPIC BLOCK: "Earth is a bucket" + bare-rock 255K derivation + 33K cliffhanger.
     Currently played in: week 2, right after Lab 0d + the uncertainty block. -->
</section></section>
<section>
<section id="now-for-real" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>4 · Now for real</h1>
<p><em>Earth is a bucket.</em></p>
</section>
<section id="the-mapping" class="slide level2">
<h2>The mapping</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>bucket</th>
<th>Earth</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tap (inflow <span class="math inline">\(F\)</span>)</td>
<td><strong>sunlight</strong></td>
</tr>
<tr class="even">
<td>drain</td>
<td><strong>infrared radiation to space</strong></td>
</tr>
<tr class="odd">
<td>water level <span class="math inline">\(h\)</span></td>
<td><strong>temperature <span class="math inline">\(T\)</span></strong></td>
</tr>
<tr class="even">
<td>drain law <span class="math inline">\(Q = kh\)</span></td>
<td><span class="math inline">\(\sigma T^4\)</span> <em>(Stefan–Boltzmann)</em></td>
</tr>
<tr class="odd">
<td>fuller → drains harder</td>
<td>warmer → radiates harder <em>(the stabilizing feedback)</em></td>
</tr>
<tr class="even">
<td>level lags the tap</td>
<td>warming lags emissions <em>(soon: the ocean sets the clock)</em></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>The payoff slide of the day — the bucket you just built wasn’t an analogy, it was the actual mathematical object of this course. Ask them to fill the right column before revealing it.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-first-calculation-live-on-the-board" class="slide level2">
<h2>The first calculation <em>(live, on the board)</em></h2>
<p>Energy in: sunlight on a disk — <span class="math inline">\(\pi R^2 S_0(1-\alpha)\)</span>. Energy out: infrared from a sphere — <span class="math inline">\(4\pi R^2 \sigma T^4\)</span>.</p>
<p><span class="math display">\[T_e = \left[\frac{S_0(1-\alpha)}{4\sigma}\right]^{1/4} \approx \mathbf{255\ K} = -18\,°\mathrm{C}\;\;(?!)\]</span></p>
<p><em>with <span class="math inline">\(S_0 = 1361\ \mathrm{W\,m^{-2}}\)</span>, <span class="math inline">\(\alpha \approx 0.30\)</span>, <span class="math inline">\(\sigma = 5.67\times10^{-8}\ \mathrm{W\,m^{-2}\,K^{-4}}\)</span></em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>formula</th>
<th>actual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mars</td>
<td>~210 K</td>
<td>~218 K ✓</td>
</tr>
<tr class="even">
<td><strong>Earth</strong></td>
<td><strong>255 K</strong></td>
<td><strong>288 K — off by 33 K</strong></td>
</tr>
<tr class="odd">
<td>Venus</td>
<td>~230 K</td>
<td><strong>735 K — off by 500 K!</strong></td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Board derivation, slowly — ask “why πR² in but 4πR² out?” before answering; sets the math culture. This is the bucket’s equilibrium step (set the budget to zero) for the planet. Venus kills “it’s distance from the Sun.”</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="k-the-most-productive-wrong-answer-in-science" class="slide level2">
<h2>33 K — the most productive wrong answer in science</h2>
<p>That gap <strong>is the greenhouse effect</strong>. Closing it:</p>
<ul>
<li><strong>Next:</strong> <em>why</em> — the layer model, then the picture professionals use</li>
<li><strong>Then:</strong> <em>when</em> — the model ticks in time; the ocean sets the clock</li>
<li><strong>Later:</strong> <em>how much</em> — feedbacks decide whether 3.7 W/m² means 2 °C or 5 °C</li>
</ul>
<aside class="notes">
<p>Honest note: 255 K is REAL — satellites measure Earth radiating at exactly this temperature. The puzzle is precise. If time remains, go straight into “why”.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section id="if-we-get-there-closing-the-33-k-gap" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>If we get there · Closing the 33 K gap</h1>
<!-- TOPIC BLOCK: selective absorption Currently played in: week 2. -->
</section>

<section>
<section id="step-1-why-the-atmosphere-intervenes" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>Step 1: Why the atmosphere intervenes</h1>

</section>
<section id="two-streams-of-light-that-barely-touch" class="slide level2">
<h2>Two streams of light that barely touch</h2>
<!-- FIGURE: normalized blackbody curves for 5800 K (Sun) and 288 K (Earth) vs wavelength, log axis — the classic "two humps with a gap near 4 µm" figure. -->
<ul>
<li>Sun (5800 K): peaks near <strong>0.5 µm</strong> — <em>shortwave</em></li>
<li>Earth (255–288 K): peaks near <strong>10–15 µm</strong> — <em>longwave</em></li>
<li>Almost <strong>no overlap</strong> → energy in and energy out are separate bookkeeping</li>
</ul>
<aside class="notes">
<p>This spectral separation is a gift — it’s why “solar in, infrared out” is a clean split and why the whole subject is tractable. GR5001 callback: they saw the Trenberth-style budget diagram; this is the physics under its two-column layout.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="who-absorbs-what" class="slide level2">
<h2>Who absorbs what</h2>
<!-- FIGURE: atmospheric absorption spectrum by gas (the stacked per-gas absorption bands figure, e.g. from Goosse or Pierrehumbert) — visible window open, IR bands owned by H2O, CO2, O3, CH4. -->
<ul>
<li><strong>N₂ + O₂ = ~99% of the air — and nearly transparent in the infrared</strong></li>
<li>The absorbers are the <em>vibrating, polar</em> trace molecules: <strong>H₂O, CO₂, CH₄, O₃, N₂O</strong></li>
<li>Nearly transparent at 0.5 µm, strongly absorbing at 10–15 µm</li>
</ul>
<aside class="notes">
<p>One sentence of molecular physics is enough: symmetric diatomic molecules have no dipole moment to grab infrared photons; triatomic benders and stretchers do. Don’t go deeper unless asked.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-greenhouse-effect-is-a-trace-gas-effect" class="slide level2">
<h2>The greenhouse effect is a <em>trace-gas</em> effect</h2>
<blockquote>
<p>“CO₂ is only 0.04% of the atmosphere!”</p>
</blockquote>
<div class="fragment">
<p>Correct — and that 0.04% (plus water vapor) is doing <strong>all</strong> of the work. Remove every trace gas and keep the 99%: Earth freezes.</p>
<aside class="notes">
<p>Reframe the talking point as the actual story. Plant (don’t fully develop) the week-9 distinction: H₂O is the biggest absorber, but it <em>condenses</em> — days of residence, slaved to temperature — so it’s a <strong>feedback</strong>, an amplifier. CO₂ is the <strong>forcing</strong>, the control knob. Lacis et al.&nbsp;2010 ran it: remove CO₂, the water vapor rains out, Earth ices over. Full treatment Nov 5.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- TOPIC BLOCK: the one-layer / N-layer greenhouse model Board-heavy. Currently played in: week 2. -->
</div>
</section></section>
<section>
<section id="step-2-one-pane-of-glass" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>Step 2: One pane of glass</h1>

</section>
<section id="the-simplest-greenhouse-setup" class="slide level2">
<h2>The simplest greenhouse: setup</h2>
<p>One atmospheric layer that is:</p>
<ul>
<li><strong>transparent</strong> to shortwave (sunlight passes through)</li>
<li><strong>perfectly absorbing</strong> in longwave (nothing gets past it)</li>
<li>radiating <span class="math inline">\(\sigma T_a^4\)</span> <strong>both up and down</strong></li>
</ul>
<!-- FIGURE: simple schematic — surface, one layer, arrows: solar to surface; surface IR absorbed by layer; layer radiates up (to space) and down (to surface). Draw this on the board first; slide is the record. -->
<aside class="notes">
<p>BOARD, not slides, for the whole derivation. Two budgets, two unknowns — ask the room to supply each term before writing it. This is the second board derivation of the course (after week 1’s T_e); same culture: they follow, not admire.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="the-derivation-record" class="slide level2">
<h2>The derivation (record)</h2>
<p><strong>Top of atmosphere:</strong> what leaves = what enters <span class="math display">\[\sigma T_a^4 = \tfrac{S_0}{4}(1-\alpha) \;\Rightarrow\; T_a = T_e = 255\ \mathrm{K}\]</span></p>
<p><strong>Surface:</strong> heated by Sun <em>and</em> by the sky <span class="math display">\[\sigma T_s^4 = \tfrac{S_0}{4}(1-\alpha) + \sigma T_a^4 \;\Rightarrow\; T_s = 2^{1/4}\,T_e \approx 303\ \mathrm{K}\]</span></p>
<aside class="notes">
<p>Pause on what fell out: the ATMOSPHERE sits at the emission temperature; the surface is warmer than both. The layer doesn’t “trap” heat — it re-radiates downward. Kill the blanket metaphor here (blankets suppress convection; Wood’s 1909 rock-salt greenhouse experiment if asked).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="three-surprises-from-one-tiny-model" class="slide level2">
<h2>Three surprises from one tiny model</h2>
<ol type="1">
<li>The <em>atmosphere</em> radiates at 255 K — the surface hides beneath it, warmer</li>
<li>The surface receives <strong>more energy from the sky than from the Sun</strong> (~340 vs ~168 W/m² in the real budget)</li>
<li>It <strong>overshoots</strong>: 303 K predicted vs 288 K observed</li>
</ol>
<aside class="notes">
<p>#2 is the intuition-breaker — let it sit. It’s in the observed surface budget (GR5001’s diagram!): downwelling longwave beats absorbed solar at the ground. #3 is the productive failure that drives the next slide.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-the-overshoot-the-best-kind-of-wrong" class="slide level2">
<h2>Why the overshoot? The best kind of wrong</h2>
<ul>
<li>The real atmosphere isn’t a <em>perfect</em> absorber (windows, wings)</li>
<li>Deeper: <strong>convection short-circuits radiation</strong> — ~100 W/m² leaves the surface as evaporation + thermals, not photons</li>
<li>Pure radiative equilibrium would make the lower atmosphere absurdly steep and unstable → convection overturns it and <strong>pins the lapse rate ≈ 6.5 K/km</strong></li>
</ul>
<div class="fragment">
<p>Automating exactly this repair = <strong>Manabe &amp; Wetherald 1967</strong> (week 1’s “most influential paper”).</p>
<aside class="notes">
<p>This is the week’s brief vertical-structure aside — the ONLY dose of RCE this week (thread returns Nov 5). GR5001 callback: their week 3 was convection; “you know why air rises — here’s what that does to the greenhouse.” M&amp;W Fig 16 from last week can reappear for one beat.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="n-panes-of-glass" class="slide level2">
<h2>N panes of glass</h2>
<p><span class="math display">\[T_s = (N+1)^{1/4}\, T_e\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>N</th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(T_s\)</span> (K)</td>
<td>255</td>
<td>303</td>
<td>336</td>
<td>361</td>
<td>…</td>
</tr>
</tbody>
</table>
<p>More absorber → warmer surface, with <strong>diminishing returns</strong> — the first hint of a logarithm.</p>
<p><strong>Venus:</strong> ~90 bar of CO₂ ≈ <em>many</em> panes → 735 K.</p>
<aside class="notes">
<p>Don’t derive N-layer on the board (HW1 problem 1 does it — say so explicitly: “your first homework problem is to earn this formula”). Venus closes the loop on week 1’s three-planet table. Runaway-greenhouse teaser: one sentence, week 9.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- TOPIC BLOCK: the emission-height picture Currently played in: week 2. The single most important conceptual model of the course's first act. -->
</section></section>
<section>
<section id="step-3-the-picture-professionals-actually-use" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>Step 3: The picture professionals actually use</h1>

</section>
<section id="where-does-earths-radiation-to-space-really-come-from" class="slide level2">
<h2>Where does Earth’s radiation to space really come from?</h2>
<p>In the CO₂/H₂O bands the atmosphere is <em>optically thick</em>: surface photons are absorbed and re-emitted many times before escaping.</p>
<p>Effectively, space “sees” radiation not from the ground but from an <strong>effective emission height</strong>:</p>
<p><span class="math display">\[z_e \approx 5\text{–}6\ \mathrm{km}, \quad \text{where } T \approx 255\ \mathrm{K}\]</span></p>
<!-- FIGURE: schematic — temperature profile (lapse rate line), emission height marked at 255 K, surface at 288 K below; a second, higher z_e after adding CO2. Best drawn as a two-panel before/after. -->
<aside class="notes">
<p>Connect back: the 255 K from week 1 is REAL — satellites measure it. This slide says <em>where</em> it lives: ~5.5 km up. The layer model was a cartoon of this.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="add-co₂-the-radiating-surface-rises" class="slide level2">
<h2>Add CO₂ → the radiating surface rises</h2>
<ol type="1">
<li>More CO₂ → atmosphere more opaque in the IR → <strong>z_e rises</strong></li>
<li>Higher = <strong>colder</strong> (lapse rate!) → planet radiates <em>less</em> to space</li>
<li>Energy imbalance → the whole column warms…</li>
<li>…until the <em>new</em> emission height is back at 255 K</li>
<li>The surface, ~6 km below along the lapse rate, ends up <strong>warmer</strong></li>
</ol>
<p><span class="math display">\[\Delta T_s \approx \Gamma \cdot \Delta z_e \qquad (\sim150\ \mathrm{m\ rise} \approx 1\ \mathrm{K})\]</span></p>
<aside class="notes">
<p>Walk the 5 steps slowly, twice if needed — this is the mental model to install for the whole course. Note what restores balance: not the surface “trapping” anything, but the planet’s radiating level sliding up a fixed temperature ladder.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="one-sentence-to-keep" class="slide level2">
<h2>One sentence to keep</h2>
<blockquote>
<p><strong>Global warming = raising the height from which Earth radiates to space — with the surface dragged warmer along the lapse rate.</strong></p>
</blockquote>
<aside class="notes">
<p>Say it, let them write it, move on. This sentence defeats arguments the layer model can’t (next block).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="this-picture-makes-free-predictions" class="slide level2">
<h2>This picture makes free predictions</h2>
<ul>
<li><strong>The stratosphere should <em>cool</em></strong> as the surface warms (it sits above the emission level) — <strong>observed</strong> ✓, and a fingerprint pure solar warming would <em>not</em> produce</li>
<li>No lapse rate → no warming from raising <span class="math inline">\(z_e\)</span> → the lapse rate itself matters (week 9: lapse-rate feedback)</li>
</ul>
<aside class="notes">
<p>Stratospheric cooling: predicted by M&amp;W 1967 (they saw it in Fig 16 last week), confirmed decades later by satellites/radiosondes. This is the honest counterweight to “models are tuned” — fingerprint predictions made before the observations existed.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- TOPIC BLOCK: band saturation, the logarithm, and the Ångström activity Currently played in: week 2. -->
</section></section>
<section>
<section id="step-4-the-125-year-old-objection" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>Step 4: The 125-year-old objection</h1>

</section>
<section id="ångström-vs-arrhenius" class="slide level2">
<h2>1900: Ångström vs Arrhenius</h2>
<blockquote>
<p>“The CO₂ absorption band is <strong>already saturated</strong> — the center of the 15 µm band absorbs everything within meters. Adding more CO₂ can’t do anything.” — Knut Ångström’s lab assistant, 1900 (paraphrased)</p>
</blockquote>
<p>This argument killed interest in Arrhenius’s work for decades. <strong>It still circulates today.</strong></p>
<p>By the end of this hour, you’ll be able to break it. <em>(That’s literally the next activity.)</em></p>
<aside class="notes">
<p>Frame it with respect — it’s a GOOD objection, and the physics community bought it for ~40 years. Don’t reveal the answer yet.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="look-at-the-actual-spectrum" class="slide level2">
<h2>Look at the actual spectrum</h2>
<!-- FIGURE: MODTRAN outgoing-IR spectrum screenshots, 280 ppm vs 560 ppm overlaid — the CO2 "bite" deepening at the WINGS while the band center barely moves. Take these from the U. Chicago MODTRAN web interface (modtran.spectral.ucar.edu / climatemodels.uchicago.edu). -->
<ul>
<li>Band <strong>center</strong>: opaque at 280 ppm, opaque at 560 ppm — Ångström was <em>right</em> about the center</li>
<li>Band <strong>wings</strong>: visibly deepening — this is where doubling acts</li>
</ul>
<aside class="notes">
<p>LIVE DEMO if wifi cooperates (U. Chicago MODTRAN): set 280 ppm, note outgoing flux; double to 560; the flux drops ~3 W/m²; zoom the band wings. Students see the forcing in measured-quantity space. Screenshots on this slide are the wifi-failure fallback — rehearse the demo once beforehand.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="why-the-response-is-a-logarithm-not-zero" class="slide level2">
<h2>Why the response is a logarithm (not zero)</h2>
<p>Each doubling widens the effective opaque interval by roughly the <strong>same spectral increment</strong>:</p>
<p><span class="math display">\[\Delta F \approx 5.35 \cdot \ln\!\left(\frac{C}{C_0}\right)\ \mathrm{W\,m^{-2}} \qquad \approx 3.7\ \mathrm{W\,m^{-2}\ per\ doubling}\]</span></p>
<ul>
<li>Saturation is <em>why it’s a log</em> — not why it’s zero</li>
<li>This is why climate speaks in <strong>doublings</strong>, and why ECS is defined <em>per doubling</em></li>
</ul>
<aside class="notes">
<p>280→560 ppm and 560→1120 ppm have the SAME forcing. Also note: this one-line formula is how CMIP-model forcings are quoted and compared — the toy is the ruler (bridge beat returns at the end).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="your-turn-break-ångström-in-pairs" class="slide level2">
<h2>Your turn: break Ångström <em>(in pairs)</em></h2>
<p>Here is the argument, verbatim:</p>
<blockquote>
<p><em>“The CO₂ band is already saturated — the atmosphere absorbs all the radiation in that band within a few hundred meters. More CO₂ cannot change the energy balance.”</em></p>
</blockquote>
<p>With your partner, write <strong>the strongest 3–4 sentence rebuttal you can</strong>. Use anything from today. Names on the slip; hand it in.</p>
<aside class="notes">
<p>Circulate with the TAs. Most pairs will find the wings; the deeper rebuttal (emission height rises regardless — a saturated band just means z_e is HIGH, not that it can’t go higher) is what the debrief adds. Slips → participation credit.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="debrief-three-independent-ways-it-fails" class="slide level2">
<h2>Debrief: three independent ways it fails</h2>
<ol type="1">
<li><strong>The wings aren’t saturated</strong> — and that’s where doubling acts (you saw it in the spectrum)</li>
<li><strong>The emission height rises regardless</strong> — saturation means <span class="math inline">\(z_e\)</span> is high, not that it’s stuck; higher is colder is less radiation</li>
<li><strong>Thin, cold upper layers always radiate less</strong> — there is no altitude where “more absorber” stops mattering</li>
</ol>
<aside class="notes">
<p>Argument 2 is the professional one — flag that pairs who found it were reasoning at the research level. Historical coda, 1 sentence: the 1940s–50s spectroscopy (partly military-funded, Plass et al.) resolved the band structure and revived CO₂ science.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
<!-- TOPIC BLOCK: scale-up & bridge for radiation Currently played in: week 2. Beat 2/3 of the weekly Play→Scale-up→Bridge template. -->
</section></section>
<section>
<section id="from-todays-toy-to-the-real-machine" class="title-slide slide level1 center" data-background-color="#1a3a5c">
<h1>From today’s toy to the real machine</h1>

</section>
<section id="scale-up-radiation-in-a-real-climate-model" class="slide level2">
<h2>Scale-up: radiation in a real climate model</h2>
<ul>
<li>Line-by-line absorption: physically exact, computationally hopeless at runtime</li>
<li>Models use <strong>band schemes</strong> (“correlated-k”), validated against line-by-line codes</li>
<li>Radiation is computed in every column, ~100 levels, every 1–3 model hours</li>
</ul>
<div class="fragment">
<p>Your layer model and a GCM’s radiation code differ in <strong>resolution, not in kind</strong>.</p>
<aside class="notes">
<p>The point of the scale-up beat every week: demystify. The radiation module of a CMIP model is the N-layer model with real spectroscopy and clever bookkeeping.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</div>
</section>
<section id="bridge-the-toy-is-the-ruler" class="slide level2">
<h2>Bridge: the toy is the ruler</h2>
<ul>
<li><strong>Backward:</strong> Manabe &amp; Wetherald 1967 = today’s chain done right the first time — real spectra + convection-pinned lapse rate → ECS ≈ 2.3 K, within today’s assessed range</li>
<li><strong>Forward:</strong> when CMIP models are compared, their CO₂ forcing is quoted through the same <span class="math inline">\(5.35\ln(C/C_0)\)</span> — the formula <em>you</em> now own</li>
</ul>
<aside class="notes">
<p>Close the loop explicitly — this is the weekly bridge sentence: “the simple model isn’t a stepping stone we discard; it’s the instrument the community measures the big models with.” Next week’s bridge is even stronger (their lab EBM is literally fit to every CMIP model).</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="before-you-leave" class="slide level2">
<h2>Before you leave</h2>
<ul>
<li><strong>Lab 0d</strong> → saved into your course repo; <strong>repo link on Courseworks</strong> if you haven’t posted it yet</li>
<li>GitHub still fighting you? Follow <strong><a href="https://dhruvbalwada.github.io/intro-climate-modeling-fall2026/labs/github_setup.html">GitHub on the LEAP hub</a></strong> or bring it to office hours — it has to work before the first homework</li>
<li><strong>Next week:</strong> we pick up wherever we stop today — closing the 33 K gap</li>
</ul>
<aside class="notes">
<p>End on the GitHub reminder — TAs chase stragglers from the Courseworks submission list.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Intro to Climate Modeling · Week 2</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>